language: node_js
node_js: '12.6.0'
sudo: false

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  on:
    branch: development
  github-token: $GITHUB_TOKEN
  local-dir: dist
  keep-history: true
  committer-from-gh: true
  target_branch: master
