language: node_js
sudo: false
node_js:
  - 10.16.0

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  on:
    branch: development
  github-token: $GITHUB_TOKEN
  local-dir: dist
    keep-history: true
  committer-from-gh: true
  target_branch: master
