language: node_js
node_js: '12.6.0'
cache:
  npm: true
  directories:
    - dist
sudo: false

install:
  - npm install

script:
  - npm build

deploy:
  provider: pages
  skip-cleanup: true
  on:
    branch: development
  github-token: $GITHUB_TOKEN
  local-dir: dist
  keep-history: true
  committer-from-gh: true
  target_branch: master
